version: 0.0 #1
os: linux
files:
  - source: / #2
    destination: /home/ec2-user/app/step2/zip #3
    overwrite: yes #4

# 1 : CodeDeploy 버전을 이야기 한다. 프로젝트 버전이 아니므로 0.0 외에 다른 버전을 사용하면 오류가 발생한다.
# 2 : CodeDeploy 에서 전달해 준 파일 중 destination 으로 이동시킬 대상을 지정한다. 루트경로(/)를 지정하면 전체 파일을 이야기한다.
# 3 : source 에서 지정된 파일을 받을 위치이다. 이후 Jar 를 실행하는 등은 destination 에서 옮긴 파일들로 진행된다.
# 4 : 기존에 파일들이 있으면 덮어쓸지 결정한다.